spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.74.233.237:3306/chatbot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 888212

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update